// Generated by Selenium IDE
package org.ual.hmis.jps105;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DeleteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws Exception {
	//System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
	//System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void delete() {
    driver.get("http://35.245.24.195:8080/");
    driver.manage().window().setSize(new Dimension(1101, 759));
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("delete1");
    driver.findElement(By.cssSelector(".form-control")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.cssSelector(".name")).getText(), is("delete1"));
    driver.findElement(By.cssSelector(".form-control")).sendKeys("delete2");
    driver.findElement(By.cssSelector(".form-control")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".item:nth-child(2) .far")).click();
    driver.findElement(By.cssSelector(".completed .remove > .btn")).click();
    driver.findElement(By.cssSelector(".fa")).click();
    assertThat(driver.findElement(By.cssSelector(".text-center")).getText(), is("No existen elementos. Añada alguno!!!"));
    driver.close();
  }
}
